[package]
authors = ["Twilight Contributors"]
categories = []
description = "Discord API models for the Twilight ecosystem."
documentation = "https://docs.rs/twilight-model"
edition = "2018"
homepage = "https://twilight.rs/chapter_1_crates/section_1_model.html"
include = ["src/**/*.rs", "Cargo.toml"]
keywords = ["discord", "discord-api", "twilight"]
license = "ISC"
name = "twilight-model"
publish = false
readme = "README.md"
repository = "https://github.com/twilight-rs/twilight.git"
version = "0.3.4"

[dependencies]
bitflags = { default-features = false, version = "1" }
serde = { default-features = false, features = ["derive"], version = "1" }
serde-value = { default-features = false, version = "0.7" }
serde_repr = { default-features = false, version = "0.1" }
tracing = { default-features = false, version = "0.1" }

[dev-dependencies]
criterion = "0.3"
serde_json = { default-features = false, features = ["alloc"], version = "1" }
serde_test = { default-features = false, version = "1" }

[[bench]]
name = "deserialization"
harness = false
path = "benches/deserialization.rs"
