[package]
authors = ["Valdemar Erk <valdemar@erk.io>"]
documentation = "https://docs.rs/twilight-model"
edition = "2018"
homepage = "https://github.com/twilight-rs/twilight"
include = ["src/*.rs", "Cargo.toml"]
keywords = ["discord", "discord-api", "twilight"]
license = "ISC"
name = "twilight-model"
publish = false
readme = "README.md"
repository = "https://github.com/twilight-rs/twilight.git"
version = "0.1.0"

[dependencies]
bitflags = { default-features = false, version = "1" }
tracing = { default-features = false, features = ["std", "attributes"], version = "0.1" }
serde = { default-features = false, features = ["derive"], version = "1" }
serde-mappable-seq = { default-features = false, version = "0.1" }
serde_repr = { default-features = false, version = "0.1" }
serde-value = { default-features = false, version = "0.6" }

[dev-dependencies]
criterion = "0.3"
serde_json = { default-features = false, features = ["alloc"], version = "1" }
serde_test = { default-features = false, version = "1" }

[[bench]]
name = "deserialization"
harness = false
