[workspace]
members = [
    # "book/tests",
    "cache/in-memory",
    "examples",
    "gateway",
    "gateway-queue",
    "http",
    "http-ratelimiting",
    "lavalink",
    "mention",
    "model",
    "standby",
    "twilight",
    "util",
    "validate",
]
