[package]
authors = ["Valdemar Erk <valdemar@erk.io>"]
documentation = "https://docs.rs/twilight-gateway"
edition = "2018"
homepage = "https://twilight.valley.cafe"
include = ["src/*.rs", "Cargo.toml"]
keywords = ["discord", "discord-api", "twilight"]
license = "ISC"
name = "twilight-gateway"
publish = false
readme = "README.md"
repository = "https://github.com/twilight-rs/twilight.git"
version = "0.1.0"

[dependencies]
async-trait = { default-features = false, version = "0.1" }
bitflags = { default-features = false, version = "1" }
twilight-http = { path = "../http" }
twilight-model = { default-features = false, path = "../model" }
futures-channel = { default-features = false, version = "0.3" }
futures-util = { default-features = false, features = ["std"], version = "0.3" }
log = { default-features = false, version = "0.4" }
once_cell = { default-features = false, features = ["std"], version = "1" }
serde = { default-features = false, features = ["derive"], version = "1" }
serde_json = { default-features = false, optional = true, version = "1" }
simd-json = { default-features = false, optional = true, version = "0.3" }
tokio = { default-features = false, features = ["net", "rt-core", "sync"], version = "0.2" }
tokio-tungstenite = { default-features = false, features = ["connect", "tls"], version = "0.10" }
url = { default-features = false, version = "2" }
# The default backend for flate2; miniz-oxide, works differently
# from the C-backed backend zlib, When you give it the sync argument
# it does not seem to update the total_in of the function to have an offset
# https://github.com/alexcrichton/flate2-rs/issues/217
flate2 = { default-features = false, features = ["zlib"], version = "1.0" }
dashmap = { default-features = false, version = "3" }

#optional
metrics = { default-features = false, optional = true, version = "0.12.1" }

[dev-dependencies]
futures = { default-features = false, version = "0.3" }
tokio = { default-features = false, features = ["rt-core", "macros"], version = "0.2" }

[features]
default = ["serde_json"]
