[package]
name = "twilight-example-model-webhook-slash"
version = "0.1.0"
authors = ["Twilight Contributors"]
edition = "2021"

[dependencies]
ed25519-dalek = "1"
hex = "0.4"
hyper = { version = "0.14", features = ["server", "http1", "runtime"] }
once_cell = "1.4"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tokio = { default-features = false, features = ["macros", "rt-multi-thread"], version = "1.0" }
tracing-subscriber = { default-features = false, features = ["fmt"], version = "0.3" }
twilight-model = { path = "../../model" }
