[package]
authors = ["Twilight Contributors"]
edition = "2018"
name = "twilight-gateway-example-intents"
version = "0.1.0"

[dependencies]
twilight-gateway = { path = "../.." }
futures = "0.3"
tracing-subscriber = "0.2"
tokio = "1.0"
