[package]
authors = ["Twilight Contributors"]
edition = "2018"
name = "twilight-http-example-slash-commands"
publish = false
version = "0.0.1"

[dependencies]
twilight-http = { path = "../.." }
twilight-model = { path = "../../../model" }
futures = "0.3"
tracing-subscriber = "0.2"
tokio = { version = "0.2", features = ["macros", "rt-core"] }
