[package]
name = "twilight-example-lavalink-basic-bot"
version = "0.1.0"
authors = ["Twilight Contributors"]
edition = "2021"

[dependencies]
futures-util = { default-features = false, version = "0.3" }
hyper = { features = ["client", "http2", "runtime"], version = "0.14" }
serde_json = { version = "1" }
tokio = { default-features = false, features = ["macros", "rt-multi-thread"], version = "1.0" }
tracing = "0.1"
tracing-subscriber = { default-features = false, features = ["fmt"], version = "0.3" }
twilight-gateway = { path = "../../gateway" }
twilight-http = { path = "../../http" }
twilight-lavalink = { path = "../../lavalink" }
twilight-model = { path = "../../model" }
twilight-standby = { path = "../../standby" }
