[package]
authors = ["Zeyla Hellyer <zeyla@hellyer.dev>"]
documentation = "https://docs.rs/twilight-http"
edition = "2018"
homepage = "https://github.com/twilight-rs/twilight"
include = ["src/*.rs", "Cargo.toml"]
keywords = ["discord", "discord-api", "twilight"]
license = "ISC"
name = "twilight-http"
publish = false
readme = "README.md"
repository = "https://github.com/twilight-rs/twilight.git"
version = "0.1.0"

[dependencies]
futures = "0.3"
twilight-model = { path = "../model" }
log = "0.4"
reqwest = "0.10"
serde = "1"
serde_json = "1"
tokio = "0.2"
percent-encoding = "2.1"

[dev-dependencies]
tokio = "0.2"
