[package]
authors = ["Twilight Contributors"]
categories = ["api-bindings", "asynchronous", "web-programming::http-client"]
description = "Discord REST API client for the Twilight ecosystem."
documentation = "https://docs.rs/twilight-http"
edition = "2018"
homepage = "https://twilight.rs/chapter_1_crates/section_2_http.html"
include = ["src/**/*.rs", "Cargo.toml"]
keywords = ["discord", "discord-api", "twilight"]
license = "ISC"
name = "twilight-http"
publish = false
readme = "README.md"
repository = "https://github.com/twilight-rs/twilight.git"
version = "0.3.6"

[dependencies]
bytes = { default-features = false, version = "1.0" }
rand = { default-features = false, features = ["std_rng", "std"], version = "0.8" }
futures-channel = { default-features = false, version = "0.3" }
futures-util = { default-features = false, features = ["std"], version = "0.3" }
hyper = { default-features = false, features = ["client", "http2", "runtime"], version = "0.14" }
hyper-rustls = { default-features = false, features = ["native-tokio"], optional = true, version = "0.22" }
hyper-tls = { default-features = false, optional = true, version = "0.5" }
native-tls = { default-features = false, features = ["alpn"], optional = true, version = "0.2.7" }
percent-encoding = { default-features = false, version = "2" }
tokio = { default-features = false, features = ["time"], version = "1.0" }
tracing = { default-features = false, features = ["std", "attributes"], version = "0.1" }
twilight-model = { default-features = false, path = "../model" }
serde = { default-features = false, features = ["derive"], version = "1" }
serde_json = { default-features = false, features = ["alloc"], version = "1" }
serde_repr = { default-features = false, version = "0.1" }

# optional
simd-json = { default-features = false, features = ["serde_impl", "swar-number-parsing"], optional = true, version = "0.3" }

[features]
default = ["rustls"]
native = ["hyper-tls", "native-tls"]
rustls = ["hyper-rustls"]

[dev-dependencies]
serde_test = { default-features = false, version = "1" }
static_assertions = { default-features = false, version = "1.1.0" }
twilight-embed-builder = { default-features = false, path = "../embed-builder" }
tokio = { default-features = false, features = ["macros", "rt-multi-thread"], version = "1.0" }
