[package]
authors = ["Valdemar Erk <valdemar@erk.io>"]
edition = "2018"
name = "twilight-gateway-example-metrics"
version = "0.1.0"

[dependencies]
twilight-gateway = { path = "../..", features = ["metrics"] }
futures = "0.3"
log = "0.4"
tracing = "0.1"
tracing-log = "0.1"
tracing-subscriber = "0.2"
tokio = { version = "0.2", features = ["macros", "rt-core"] }
metrics-runtime = "0.13"
