[package]
authors = ["Valdemar Erk <valdemar@erk.io>"]
edition = "2018"
name = "twilight-http-example-allowed-mentions"
publish = false
version = "0.0.1"

[dependencies]
twilight-http = { path = "../.." }
twilight-model = { path = "../../../model" }
pretty_env_logger = "0.3"
tokio = { version = "0.2", features = ["macros", "rt-core"] }
