[package]
authors = ["Zeyla Hellyer <zeyla@hellyer.dev>"]
edition = "2018"
name = "dawn-http-example-get-message"
publish = false
version = "0.0.1"

[dependencies]
dawn-http = { path = "../.." }
dawn-model = { path = "../../../model" }
futures = "0.3"
pretty_env_logger = "0.3"
tokio = "0.2"
