[package]
authors = ["Twilight Contributors"]
edition = "2021"
name = "twilight-example-gateway-intents"
version = "0.1.0"

[dependencies]
futures-util = { default-features = false, version = "0.3" }
tokio = { default-features = false, features = ["macros", "rt-multi-thread"], version = "1.0" }
tracing-subscriber = { default-features = false, features = ["fmt"], version = "0.3" }
twilight-gateway = { path = "../../gateway" }
