[package]
authors = ["Twilight Contributors"]
edition = "2021"
name = "twilight-example-gateway-metrics"
version = "0.1.0"

[dependencies]
futures-util = { default-features = false, version = "0.3" }
log = { default-features = false, version = "0.4" }
metrics-runtime = { default-features = false, features = ["metrics-exporter-log", "metrics-observer-json"], version = "0.13" }
tokio = { default-features = false, features = ["macros", "rt-multi-thread"], version = "1.0" }
tracing-subscriber = { default-features = false, features = ["fmt", "tracing-log"], version = "0.3" }
twilight-gateway = { path = "../../gateway", features = ["metrics"] }
