[package]
authors = ["Twilight Contributors"]
categories = []
description = "Discord Gateway connection queue implementation for the Twilight ecosystem."
documentation = "https://docs.rs/twilight-gateway-queue"
edition = "2018"
homepage = "https://twilight.rs/"
include = ["src/**/*.rs", "Cargo.toml"]
keywords = ["discord", "discord-api", "twilight"]
license = "ISC"
name = "twilight-gateway-queue"
publish = false
readme = "README.md"
repository = "https://github.com/twilight-rs/twilight.git"
version = "0.2.1"

[dependencies]
futures-channel = { default-features = false, features = ["sink"], version = "0.3" }
futures-util = { default-features = false, features = ["std", "sink"], version = "0.3" }
tokio = { default-features = false, features = ["net", "rt-multi-thread", "sync"], version = "1.0" }
tracing = { default-features = false, features = ["std", "attributes"], version = "0.1" }
twilight-http = { path = "../../http", default-features = false }

[dev-dependencies]
static_assertions = { default-features = false, version = "1" }

[features]
default = ["rustls"]
native = ["twilight-http/native"]
rustls = ["twilight-http/rustls"]
