[package]
authors = ["Twilight Contributors"]
edition = "2018"
name = "twilight-gateway-example-request-members"
publish = false
version = "0.0.1"

[dependencies]
twilight-gateway = { path = "../.." }
twilight-model = { path = "../../../model"}
futures = "0.3"
tracing-subscriber = "0.2"
tokio = { version = "1.0", features = ["macros", "rt-multi-thread"] }
