[package]
name = "twilight-lavalink-basic-lavalink-bot"
version = "0.1.0"
authors = ["Twilight Contributors"]
edition = "2018"

[dependencies]
futures = "0.3"
hyper = { features = ["client", "http2", "runtime"], version = "0.14" }
tracing = "0.1"
tracing-subscriber = "0.2"
serde_json = { version = "1" }
tokio = { features = ["macros", "rt-multi-thread"], version = "1.0" }
twilight-gateway = { path = "../../../gateway" }
twilight-http = { path = "../../../http" }
twilight-lavalink = { path = "../.." }
twilight-model = { path = "../../../model" }
twilight-standby = { path = "../../../standby" }
