[package]
authors = ["Twilight Contributors"]
edition = "2021"
name = "twilight-example-http-allowed-mentions"
publish = false
version = "0.0.1"

[dependencies]
tokio = { default-features = false, features = ["macros", "rt-multi-thread"], version = "1.0" }
tracing-subscriber = { default-features = false, features = ["fmt"], version = "0.3" }
twilight-http = { path = "../../http" }
twilight-model = { path = "../../model" }
