[package]
authors = ["Twilight Contributors"]
edition = "2018"
name = "twilight-examples-http-allowed-mentions"
publish = false
version = "0.0.1"

[dependencies]
twilight-http = { path = "../../http" }
twilight-model = { path = "../../model" }
tracing-subscriber = "0.2"
tokio = { version = "1.0", features = ["macros", "rt-multi-thread"] }
