[package]
authors = ["Twilight Contributors"]
categories = []
description = "Advertisement crate for the twilight ecosystem; please use the individual crates instead."
documentation = "https://docs.rs/twilight"
edition = "2021"
homepage = "https://twilight.rs"
include = ["src/**/*.rs", "Cargo.toml"]
keywords = ["discord", "discord-api", "twilight"]
license = "ISC"
name = "twilight"
publish = false
repository = "https://github.com/twilight-rs/twilight"
readme = "../README.md"
rust-version = "1.57"
version = "0.8.0"

[dev-dependencies]
futures = { default-features = false, version = "0.3" }
tokio = { default-features = false, features = ["macros", "rt-multi-thread"], version = "1.0" }
twilight-cache-inmemory = { default-features = false, path = "../cache/in-memory" }
twilight-command-parser = { default-features = false, path = "../command-parser" }
twilight-embed-builder = { default-features = false, path = "../embed-builder" }
twilight-gateway = { default-features = false, features = ["rustls-native-roots"], path = "../gateway" }
twilight-http = { default-features = false, features = ["rustls-native-roots"], path = "../http" }
twilight-lavalink = { default-features = false, path = "../lavalink" }
twilight-mention = { default-features = false, path = "../mention" }
twilight-model = { default-features = false, path = "../model" }
twilight-standby = { default-features = false, path = "../standby" }
twilight-util = { default-features = false, path = "../util" }

# Depend on at least this version to fix an issue with `minvers` CI and
# `futures`
proc-macro-hack = { default-features = false, version = "0.5.7" }
