[package]
authors = ["Twilight Contributors"]
categories = []
description = "Advertisement crate for the twilight ecosystem; please use the individual crates instead."
documentation = "https://docs.rs/twilight"
edition = "2021"
homepage = "https://twilight.rs"
include = ["src/**/*.rs"]
keywords = ["discord", "discord-api", "twilight"]
license = "ISC"
name = "twilight"
publish = false
repository = "https://github.com/twilight-rs/twilight"
readme = "../README.md"
rust-version = "1.60"
version = "0.11.0"

[dev-dependencies]
futures = { default-features = false, version = "0.3" }
tokio = { default-features = false, features = ["macros", "rt-multi-thread"], version = "1.0" }
tracing-log = { default-features = false, features = ["log-tracer", "std"], version = "0.1" }
twilight-cache-inmemory = { default-features = false, path = "../cache/in-memory" }
twilight-embed-builder = { default-features = false, path = "../embed-builder" }
twilight-gateway = { default-features = false, features = ["rustls-native-roots"], path = "../gateway" }
twilight-gateway-queue = { default-features = false, features = ["rustls-native-roots"], path = "../gateway-queue" }
twilight-http = { default-features = false, features = ["rustls-native-roots"], path = "../http" }
twilight-http-ratelimiting = { default-features = false, path = "../http-ratelimiting" }
twilight-lavalink = { default-features = false, path = "../lavalink" }
twilight-mention = { default-features = false, path = "../mention" }
twilight-model = { default-features = false, path = "../model" }
twilight-standby = { default-features = false, path = "../standby" }
twilight-util = { default-features = false, path = "../util" }
twilight-validate = { default-features = false, path = "../validate" }
