[package]
authors = ["Twilight Contributors"]
categories = []
description = "Advertisement crate for the twilight ecosystem; please use the individual crates instead."
documentation = "https://docs.rs/twilight"
edition = "2021"
homepage = "https://twilight.rs"
include = ["src/**/*.rs", "../README.md"]
keywords = ["discord", "discord-api", "twilight"]
license = "ISC"
name = "twilight"
publish = true
repository = "https://github.com/twilight-rs/twilight"
readme = "../README.md"
rust-version = "1.60"
version = "0.13.0"

[dev-dependencies]
anyhow = { default-features = false, features = ["std"], version = "1" }
futures = { default-features = false, version = "0.3" }
tokio = { default-features = false, features = ["macros", "rt-multi-thread"], version = "1.0" }
twilight-cache-inmemory = { default-features = false, path = "../twilight-cache-inmemory", version = "0.13.0" }
twilight-gateway = { default-features = false, features = ["rustls-native-roots"], path = "../twilight-gateway", version = "0.13.0" }
twilight-gateway-queue = { default-features = false, features = ["rustls-native-roots"], path = "../twilight-gateway-queue", version = "0.13.0" }
twilight-http = { default-features = false, features = ["rustls-native-roots"], path = "../twilight-http", version = "0.13.0" }
twilight-http-ratelimiting = { default-features = false, path = "../twilight-http-ratelimiting", version = "0.13.0" }
twilight-lavalink = { default-features = false, path = "../twilight-lavalink", version = "0.13.0" }
twilight-mention = { default-features = false, path = "../twilight-mention", version = "0.13.0" }
twilight-model = { default-features = false, path = "../twilight-model", version = "0.13.2" }
twilight-standby = { default-features = false, path = "../twilight-standby", version = "0.13.0" }
twilight-util = { default-features = false, path = "../twilight-util", version = "0.13.1" }
twilight-validate = { default-features = false, path = "../twilight-validate", version = "0.13.1" }
