[package]
authors = ["Twilight Contributors"]
categories = []
description = "Advertisement crate for the twilight ecosystem; please use the individual crates instead."
documentation = "https://docs.rs/twilight"
edition = "2018"
homepage = "https://twilight.rs"
include = ["src/**/*.rs", "Cargo.toml"]
keywords = ["discord", "discord-api", "twilight"]
license = "ISC"
name = "twilight"
publish = false
repository = "https://github.com/twilight-rs/twilight"
readme = "../README.md"
version = "0.2.2"

[dev-dependencies]
futures = { default-features = false, version = "0.3" }
tokio = { default-features = false, features = ["macros", "rt-multi-thread"], version = "1.0" }
tracing-log = { default-features = false, features = ["log-tracer", "std"], version = "0.1" }
twilight-cache-inmemory = { default-features = false, path = "../cache/in-memory" }
twilight-command-parser = { path = "../command-parser" }
twilight-embed-builder = { default-features = false, path = "../embed-builder" }
twilight-gateway = { default-features = false, features = ["rustls"], path = "../gateway" }
twilight-http = { default-features = false, features = ["rustls"], path = "../http" }
twilight-lavalink = { path = "../lavalink" }
twilight-mention = { default-features = false, path = "../mention" }
twilight-model = { path = "../model" }
twilight-standby = { path = "../standby" }
twilight-util = { default-features = false, path = "../util" }
