[package]
authors = ["Twilight Contributors"]
categories = []
description = "Advertisement crate for the twilight ecosystem; please use the individual crates instead."
documentation = "https://docs.rs/twilight"
edition = "2021"
homepage = "https://twilight.rs"
include = ["src/**/*.rs", "../README.md"]
keywords = ["discord", "discord-api", "twilight"]
license = "ISC"
name = "twilight"
publish = false
repository = "https://github.com/twilight-rs/twilight"
readme = "../README.md"
rust-version = "1.60"
version = "0.11.0"

[dev-dependencies]
anyhow = { default-features = false, features = ["std"], version = "1" }
futures = { default-features = false, version = "0.3" }
tokio = { default-features = false, features = ["macros", "rt-multi-thread"], version = "1.0" }
twilight-cache-inmemory = { default-features = false, path = "../cache/in-memory", version = "0.11.0" }
twilight-embed-builder = { default-features = false, path = "../embed-builder", version = "0.11.0" }
twilight-gateway = { default-features = false, features = ["rustls-native-roots"], path = "../gateway", version = "0.11.0" }
twilight-gateway-queue = { default-features = false, features = ["rustls-native-roots"], path = "../gateway-queue", version = "0.11.0" }
twilight-http = { default-features = false, features = ["rustls-native-roots"], path = "../http", version = "0.11.0" }
twilight-http-ratelimiting = { default-features = false, path = "../http-ratelimiting", version = "0.11.0" }
twilight-lavalink = { default-features = false, path = "../lavalink", version = "0.11.0" }
twilight-mention = { default-features = false, path = "../mention", version = "0.11.0" }
twilight-model = { default-features = false, path = "../model", version = "0.11.1" }
twilight-standby = { default-features = false, path = "../standby", version = "0.11.0" }
twilight-util = { default-features = false, path = "../util", version = "0.11.0" }
twilight-validate = { default-features = false, path = "../validate", version = "0.11.0" }
